JuliaWeb/WebSockets.jl

- REQUIRE
- src/WebSockets.jl
Use Compat
- send_fragment: Rewrite using binary literals and new constructor syntax
- WebSocketFragment constructor: remove deprecated bool()
Drop julia 0.2 support
Also drop prerelease support for HttpCommon and HttpServer
> Modernize WebSockets

- src/WebSockets.jl
After checking out to Websockets master, in [Escher](https://github.com/shashi/Escher.jl), we were getting these error messages as you can see in https://github.com/shashi/Escher.jl/issues/66#issuecomment-134385320.
```julia
ERROR (unhandled task failure): MethodError: `lowercase` has no method matching lowercase(::Bool)
in is_websocket_handshake at /Users/rohitvarkey/.julia/v0.4/WebSockets/src/WebSockets.jl:332
in on_message_complete at /Users/rohitvarkey/.julia/v0.4/HttpServer/src/HttpServer.jl:358
in on_message_complete at /Users/rohitvarkey/.julia/v0.4/HttpServer/src/RequestParser.jl:99
in http_parser_execute at /Users/rohitvarkey/.julia/v0.4/HttpParser/src/HttpParser.jl:106
in process_client at /Users/rohitvarkey/.julia/v0.4/HttpServer/src/HttpServer.jl:330
in anonymous at …
```
> Fix lowercase and decode errors.

- src/WebSockets.jl
- test/runtests.jl
This fixes fatal errors on Julia 0.3 - specifically trying to construct with `UInt*` types without `@compat`.
Adds self-documenting constants
refactors write_fragment and read_frame to take `IO` object instead of `WebSocket`
Adds test for the above two functions
@astrieanna do check
> Fixes and a some tests

- src/WebSockets.jl
- test/runtests.jl
Firefox seems to have changed the WebSocket connection request header. The request I was receiving on doing 
```javascript
ws = new WebSocket("ws://localhost:5557/socket/toolbar.jl?w=1272&h=374")
```
in a Firefox console was
```julia
req = === Resource ====
resource: /socket/toolbar.jl?w=1272&h=374
method: GET
Headers:
Connection: keep-alive, Upgrade
Cookie: csrftoken=I7fHePfOC83O0T17X9CS7st3h3VUoZoG
Sec-WebSocket-Version: 13
http_minor: 1
Keep-Alive: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Origin: http://localhost:5557
Sec-WebSocket-Key: EKPNFAgXUxZHkDGpWOIfsA==
Sec-WebSocket-Extensions: permessage-deflate
Host: localhost:5557
Upgrade: websocket
Pragma: no-cache
http_major: 1 …
```
> Fixes `is_websocket_handshake`  for websocket connections in Firefox.

- src/WebSockets.jl
My editor keeps on removing that extra space inside of `is_websocket_handshake()`.  Oh well.  This should close #41.
> Update for Nettle API breakage

- .travis.yml
- REQUIRE
- src/WebSockets.jl
This removes the Nettle.jl dependency, which often causes install problems for Juno.
Since this is just a sha1 hash it could probably be replaced by SHA.jl, but MbedTLS is used by the rest of the web stack anyway.
> Replace nettle with mbedtls

- src/WebSockets.jl
- test/runtests.jl
`bytestring` -> `String(copy())`. This does not need a Compat min version bump. Also supersedes #55 I think.
> Fix bytestring depwarn

- REQUIRE
- examples/chat-client.html
- examples/chat.jl
- examples/repl-client.html
- examples/server.jl
- src/WebSockets.jl
- test/runtests.jl
modified:   REQUIRE                           Compat version covering…… relevant changes in 0.6
modified:   examples/chat-client.html  Prepending messages -> Appending.
modified:   examples/chat.jl                0.6 update (take_buf, Array constructors)
modified:   examples/repl-client.html   Prepending messages -> Appending. Javascript feedback, no script error when connection close.
modified:   examples/server.jl              0.6 update (take_buf, Array constructors). 'Eval' error handling and feedback. More type stability.
modified:   src/WebSockets.jl               0.6 update (take_buf, Array constructors). Precompilation.
modified:   test/runtests.jl                   0.6 update (take_buf, Array constructors)
> Dropping Julia 0.4, upgrade to 0.5 and 0.6. Fix examples.

- .travis.yml
- REQUIRE
- src/WebSockets.jl
.travis.yml              Reinstated Julia 0.4 tests
REQUIRE                Compat version down to 0.9.5
src/WebSockets.jl  Removed dead code for Julia 0.3
Four-space indents
Comment code -> Inline docs everywhere
> Reinstate 0.4, clean-up

- src/WebSockets.jl
While implementing a server accepting WebSocket connections and wanting to gracefully shut it down (including first closing the connections), I ran into the following issue.
As I do not mind if clients go away, I'm ignoring `WebSocketClosedError`s around the `read` calls in my `WebSocketHandler`s. Hence when closing a connection from the server's side, I wouldn't expect any errors to be generated. However, depending on the situation I received a number of different errors.
This pointed me in the direction of what I believe to be some issues related to how closing a WebSocket is handled, which this PR tries to address.
These issues are mainly related to when the server initiates closing the connection and another task is `read`ing from the WebSocket. In this case, the `read` call may …
> Improve closing connections

- src/WebSockets.jl
```
websocket_handshake(request,client) 
-> true or false
```
On false handshakes, the handler is never called with a WebSocket already in a closing state.
> mod: src/WebSockets.jl 	Now exits without calling handler after unaccepted handshakes

- test/browsertest.html
- test/browsertest.jl
- test/browsertest2.html
- test/functions_log_test.jl
- test/functions_open_browsers.jl
- test/functions_server.jl
- test/handler_functions_events.jl
- test/handler_functions_websockets_general_test.jl
- test/handler_functions_websockets_subprotocol_test.jl
```
mod:   test/browsertest.jl      Ws conversation is now left fully to browsers.
Prints a performance summary at the end.
mod:   test/browsertest.html    Less code duplication, simplified conversation.
Navigates to browsertest2.html when exitmsg is received.
new:   test/browsertest2.html   Adds one binary socket. Sends binary image data with increasing
image size. Displays received images. Logs conversation on page.
mod:   test/functions_log_test.jl                   clog now returns nothing, for type stability.
mod:   test/functions_server.jl                     Also serves browsertest2.html. The served
response specifies the http socket close after.
mod:   test/handler_functions_events.jl             Removed accidentally returned string, ev_listen.
mod: …
```
> Binary browser test, performance logging

- examples/chat-client.html
Sending a pull request, to follow up on https://github.com/JuliaWeb/WebSockets.jl/issues/85
> removing the dependency on jquery. Using es6

- src/WebSockets.jl
> Only copy String bytes if masked

- src/HTTP.jl
And we're 0.7 only by now... Hope the compat_stdout function didn't do any more tricks besides giving back stdout ;)
> HTTP removed compat_stdout

- README.md
- logutils/logutils_ws.jl
- src/HTTP.jl
- src/show_ws.jl
- test/show_test.jl
- test/throttling_test.jl
modified:   README.md	Example with (suppressed) output
modified:   src/HTTP.jl Keyword arguments: ServerWS, serve
modified:   src/show_ws.jl  Drop "application/juno+inline"
Base.show for ServerWS
modified:   test/show_test.jl Test all this
modified:   test/throttling_test.jl Test serve keywords
Refer issue #128
> Keyword argument constructors, show types, README update

- benchmark/functions_open_browsers.jl
- test/timeout/limited life websockets.html
- test/timeout/timeout.jl
- test/timeout/timeout_functions.jl
Added prior to upgrading to HTTP 0.8, for comparison.
modified:   benchmark/functions_open_browsers.jl  # Use WebSocketLogger
new file:   test/timeout/limited life websockets.html # Timeout client side
new file:   test/timeout/timeout.jl        # Browser client, Julia client tests
new file:   test/timeout/timeout_functions.jl # Browser client, Julia client functions
> Stricter ad-hoc tests for timeout up to 8192 s / 42 simultaneous.

- README.md
From what I understand `WSServer` has been renamed to `ServerWS`, so I've updated the example in the README to reflect that.
> change README to WebSockets.ServerWS

- src/HTTP.jl
- test/client_serverWS_test.jl
Mux uses this code and passes the IP address directly (say `localhost = ip"0.0.0.0"::IPAddr`). In this way `serve` supports both passing the string and passing the `IPAddr` object.
> allow IPAddr in serve

- examples/inbox_outbox.jl
This is blatantly copied from 
https://discourse.julialang.org/t/async-calls-to-websockets-read-and-write-methods/26405/5
Changes compared to the posted example:
- Comment
- Drop using Test
- close(outbox) -> close(inbox)
- debug log messages
> new file:   examples/inbox_outbox.jl

- src/WebSockets.jl
- test/error_test.jl
- test/frametest.jl
Got into a debugging session, where the browser would just close the socket because of julia's JIT lag on first request.
The error on the julia side was a bounds error, which is just pretty uninformative.
This improves the situation for an error.
I now also warmup the server by calling the handler with a websocket request:
```julia
headers = [
"Host" => "127.0.0.1",
"User-Agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0",
"Accept" => "*/*",
"Accept-Encoding" => "gzip, deflate, br",
"Accept-Language" => "de,en-US;q=0.7,en;q=0.3",
"Cache-Control" => "no-cache",
"Connection" => "keep-alive, Upgrade",
"Dnt" => "1",
"Origin" => "https://localhost",
"Pragma" => "no-cache",
"Sec-Websocket-Extensions" => "permessage-deflate",
"Sec-Websocket-Key" => …
```
> improve error on client abrupt close

- src/WebSockets.jl
- test/client_listen_test.jl
- test/client_serverWS_test.jl
- test/client_test.jl
Close #169
In particular see In https://github.com/JuliaWeb/WebSockets.jl/issues/169#issuecomment-758198121 for additional details
This PR started by reverting to the "old" working code, but it may evolve differently if there is any potentially better solution. Moreover, it would be valuable to find a way for testing this case.
> Fix "MbedTLS.SSLContext does not support byte I/O"
